# Generated by Django 4.2.7 on 2026-09-25 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Bo'lim nomi")),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': "Bo'lim",
                'verbose_name_plural': "Bo'limlar",
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='F.I.Sh.')),
                ('position', models.CharField(choices=[('rahbar', "Bo'lim boshlig'i"), ('bosh_mutaxassis', 'Bosh mutaxassis'), ('mutaxassis', 'Mutaxassis'), ('inspektor', 'Inspektor'), ('metodist', 'Metodist'), ('boshqa', 'Boshqa')], default='mutaxassis', max_length=100, verbose_name='Lavozim')),
                ('position_custom', models.CharField(blank=True, max_length=200, verbose_name='Maxsus lavozim')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('reception_hours', models.CharField(blank=True, max_length=200, verbose_name='Qabul vaqti')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/', verbose_name='Foto')),
                ('bio', models.TextField(blank=True, verbose_name='Biografiya')),
                ('is_management', models.BooleanField(default=False, verbose_name='Rahbariyat')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff_app.department', verbose_name="Bo'lim")),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['order', 'full_name'],
            },
        ),
    ]
