# Generated by Django 4.2.7 on 2026-10-06 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_app', '0002_position_staff_new_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='position',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='new_position',
            new_name='position',
        ),
    ]
