# Generated by Django 4.2.7 on 2026-09-25 05:17

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Sarlavha')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Mazmuni')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Nomi')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Fayl')),
                ('category', models.CharField(choices=[('qonun', "Qonunlar va me'yoriy hujjatlar"), ('buyruq', 'Buyruq va farmonlar'), ('dastur', "Ta'lim dasturlari"), ('hisobot', 'Hisobotlar'), ('boshqa', 'Boshqalar')], default='boshqa', max_length=50, verbose_name='Kategoriya')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default="Tuproqqal'a Tuman MTB", max_length=200, verbose_name='Tashkilot nomi')),
                ('organization_full_name', models.CharField(default="Tuproqqal'a Tuman Maktabgacha va Maktab Ta'limi Bo'limi", max_length=500, verbose_name="To'liq nomi")),
                ('address', models.CharField(default="Qashqadaryo viloyati, Tuproqqal'a tumani", max_length=300, verbose_name='Manzil')),
                ('phone', models.CharField(default='+998 65 000-00-00', max_length=20, verbose_name='Telefon')),
                ('phone2', models.CharField(blank=True, max_length=20, verbose_name='Telefon 2')),
                ('email', models.EmailField(default='info@tuproqqala-talim.uz', max_length=254, verbose_name='Email')),
                ('working_hours', models.CharField(default='Dushanba-Juma: 9:00 - 18:00', max_length=100, verbose_name='Ish vaqti')),
                ('about_text', ckeditor.fields.RichTextField(blank=True, verbose_name="Haqida ma'lumot")),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="Ko'rsatkich")),
                ('value', models.CharField(max_length=50, verbose_name='Qiymat')),
                ('icon', models.CharField(default='fas fa-school', max_length=100, verbose_name='Icon (FontAwesome class)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistikalar',
                'ordering': ['order'],
            },
        ),
    ]
