# Generated by Django 4.2.7 on 2026-09-25 05:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Maktab nomi')),
                ('school_type', models.CharField(choices=[('maktab', "Umumta'lim maktabi"), ('maktabgacha', "Maktabgacha ta'lim muassasasi"), ('maxsus', "Maxsus ta'lim muassasasi"), ('litsey', 'Akademik litsey'), ('kasb', 'Kasb-hunar kolleji')], default='maktab', max_length=30, verbose_name='Turi')),
                ('number', models.CharField(blank=True, max_length=20, verbose_name='Tartib raqami')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('director_name', models.CharField(blank=True, max_length=200, verbose_name='Direktor F.I.Sh.')),
                ('director_phone', models.CharField(blank=True, max_length=50, verbose_name='Direktor telefoni')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name="O'quvchilar soni")),
                ('teacher_count', models.PositiveIntegerField(default=0, verbose_name="O'qituvchilar soni")),
                ('image', models.ImageField(blank=True, null=True, upload_to='schools/', verbose_name='Rasm')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Tavsif')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name="Ta'sis yili")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Ta'lim muassasasi",
                'verbose_name_plural': "Ta'lim muassasalari",
                'ordering': ['school_type', 'number'],
            },
        ),
    ]
